import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { forwardSearch, inverseSearch, parseSyncTex } from "./synctex";

// Generated by pdflatex (TeX Live 2026) from a 3-page article whose page 3 comes from
// \input{sections/chapter}; build paths were rewritten to /tmp/writer-build-fixture.
const load = async () =>
  parseSyncTex(
    await readFile(join(import.meta.dirname, "fixtures/sample-synctex.gz")),
    "/tmp/writer-build-fixture",
  );

describe("SyncTeX", () => {
  it("maps only project sources", async () => {
    const sync = await load();
    expect([...sync.inputs.values()].sort()).toEqual(["main.tex", "sections/chapter.tex"]);
    expect(sync.pages.size).toBe(3);
  });
  it("finds the typeset position of a source line and maps it back", async () => {
    const sync = await load();
    const section = forwardSearch(sync, "main.tex", 5);
    expect(section?.page).toBe(1);
    // US letter: 1in margin + the article class text block starts near 1.5in from the left.
    expect(section?.x).toBeGreaterThan(72);
    expect(section?.x).toBeLessThan(200);
    expect(section?.y).toBeGreaterThan(72);
    expect(section?.y).toBeLessThan(300);
    const back = inverseSearch(
      sync,
      section?.page ?? 0,
      (section?.x ?? 0) + 5,
      (section?.y ?? 0) + (section?.height ?? 0) / 2,
    );
    expect(back).toEqual({ file: "main.tex", line: 5 });
  });
  it("follows \\input files onto later pages", async () => {
    const sync = await load();
    const chapter = forwardSearch(sync, "sections/chapter.tex", 3);
    expect(chapter?.page).toBe(3);
    expect(
      inverseSearch(sync, 3, (chapter?.x ?? 0) + 5, (chapter?.y ?? 0) + (chapter?.height ?? 0) / 2),
    ).toEqual({ file: "sections/chapter.tex", line: 3 });
    expect(forwardSearch(sync, "missing.tex", 1)).toBeNull();
  });
  it("maps a click on page 2 to the filler line typeset there", async () => {
    const sync = await load();
    const hit = inverseSearch(sync, 2, 150, 120);
    expect(hit?.file).toBe("main.tex");
    const there = forwardSearch(sync, "main.tex", hit?.line ?? 0);
    expect(there?.page).toBe(2);
  });
});
